# User Modeling
## Goal 
- Building the first version of the review simulator

## importing dependencies

In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from rouge_score import rouge_scorer as rouge_module


import warnings
warnings.filterwarnings('ignore')

In [2]:
#loading the data into the notebook 
df = pd.read_csv("/kaggle/input/datasets/ravirajbabasomane/amazon-reviews-2023/Amazon_reviews_2023.csv")

In [3]:
df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5,Such a lovely scent but not overpowering.,This spray is really nice. It smells really go...,[],B00YQ6X8EO,B00YQ6X8EO,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2020-05-05 14:08:48.923,0,True
1,4,Works great but smells a little weird.,"This product does what I need it to do, I just...",[],B081TJ8YS3,B081TJ8YS3,AGKHLEW2SOWHNMFQIJGBECAF7INQ,2020-05-04 18:10:55.070,1,True
2,5,Yes!,"Smells good, feels great!",[],B07PNNCSP9,B097R46CSY,AE74DYR3QUGVPZJ3P7RFWBGIX7XQ,2020-05-16 21:41:06.052,2,True
3,1,Synthetic feeling,Felt synthetic,[],B09JS339BZ,B09JS339BZ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,2022-01-28 18:13:50.220,0,True
4,5,A+,Love it,[],B08BZ63GMJ,B08BZ63GMJ,AFQLNQNQYFWQZPJQZS6V3NZU4QBQ,2020-12-30 10:02:43.534,0,True

## Data Exploration

### Column Description

- Rating: Users provide ratings (on a scale of 1 to 5) for various products.
  
- Title:Concise titles summarizing the content of each review. 
- Text: Detailed textual descriptions of users’ experiences with the products.
- Images: Associated images (if available) related to the reviewed items. 
- ASIN (Amazon Standard Identification Number): Unique identifiers for the products.
- Parent ASIN: Identifiers for parent products (if applicable). 
- User ID: Unique identifiers for the reviewers. 
- Timestamp: Date and time when the review was posted. 
- Helpful Votes: Count of helpful votes received for each review.

- Verified Purchase: Indicates whether the reviewer made a verified purchase. Researchers and practitioners can leverage this dataset for tasks such as sentiment analysis, recommendation systems, and natural language processing. It provides valuable insights into user preferences and product quality on the Amazon platform.

In [4]:
print("=== DATASET OVERVIEW ===")
print(f"Shape: {df.shape}")
print(f"\nColumn dtypes:\n{df.dtypes}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nDuplicate rows: {df.duplicated().sum()}")

=== DATASET OVERVIEW ===
Shape: (701528, 10)

Column dtypes:
rating                int64
title                object
text                 object
images               object
asin                 object
parent_asin          object
user_id              object
timestamp            object
helpful_vote          int64
verified_purchase      bool
dtype: object

Missing values:
rating                 0
title                160
text                 212
images                 0
asin                   0
parent_asin            0
user_id                0
timestamp              0
helpful_vote           0
verified_purchase      0
dtype: int64

Duplicate rows: 7275

### 1. Checking the Schema first 
Before anything else — lets know exactly what fields we have. Amazon Reviews schema varies by version.

In [5]:
## understanding the schema of the review dataset 
df.iloc[0].to_dict()

{'rating': 5,
 'title': 'Such a lovely scent but not overpowering.',
 'text': "This spray is really nice. It smells really good, goes on really fine, and does the trick. I will say it feels like you need a lot of it though to get the texture I want. I have a lot of hair, medium thickness. I am comparing to other brands with yucky chemicals so I'm gonna stick with this. Try it!",
 'images': '[]',
 'asin': 'B00YQ6X8EO',
 'parent_asin': 'B00YQ6X8EO',
 'user_id': 'AGKHLEW2SOWHNMFQIJGBECAF7INQ',
 'timestamp': '2020-05-05 14:08:48.923',
 'helpful_vote': 0,
 'verified_purchase': True}

In [6]:
#checking the columns in the data set 
df.columns.tolist()

['rating',
 'title',
 'text',
 'images',
 'asin',
 'parent_asin',
 'user_id',
 'timestamp',
 'helpful_vote',
 'verified_purchase']

### 2.User history Depth 
This is our most critical check. Users with fewer than 20 reviews cannot build a believable persona

- the results here are quite worse to build the prototype i will use users with 5 or more reviews

In [7]:
# Reviews per user

user_counts = df.groupby('user_id').size()
user_counts.describe()

count    631986.000000
mean          1.110037
std           0.753202
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max         165.000000
dtype: float64

In [8]:
# How many viable user?
five_viable = user_counts[user_counts >= 5]
ten_viable = user_counts[user_counts >= 10]
twenty_viable = user_counts[user_counts >= 20]

print(f"""The number of users with five reviews or more are {len(five_viable)},
        The number of users with ten reviews or more are {len(ten_viable)},
        while the number of users with twenty reviews or more are {len(twenty_viable)}""")

The number of users with five reviews or more are 1620,
        The number of users with ten reviews or more are 330,
        while the number of users with twenty reviews or more are 117

In [9]:
# Distribution shape
user_counts.value_counts().head(20)
# expect heavy power law: that is this should be less than the above because above we are asking for greater than or equal to 5

1     583553
2      39274
3       5713
4       1826
5        558
6        351
7        181
8        130
9         70
11        35
10        35
13        33
12        26
16        20
15        20
14        19
17        14
21         9
26         8
24         8
Name: count, dtype: int64

### 3.Rating Behaviour
we need to understand how users rate — not just globally, but per user. This feeds directly into our persona rating model.

In [10]:
# Global rating distribution
df['rating'].value_counts().sort_index()

rating
1    102080
2     43034
3     56307
4     79381
5    420726
Name: count, dtype: int64

In [11]:
#Per-user avg rating
df.groupby('user_id')['rating'].mean().describe()

count    631986.000000
mean          3.948681
std           1.487903
min           1.000000
25%           3.000000
50%           5.000000
75%           5.000000
max           5.000000
Name: rating, dtype: float64

In [12]:
# Per-user rating variance
df.groupby('user_id')['rating'].std().describe()

count    48433.000000
mean         0.697705
std          0.918379
min          0.000000
25%          0.000000
50%          0.000000
75%          1.414214
max          2.828427
Name: rating, dtype: float64

In [13]:
#Rating over time
''' checking how users rate over time that is if a users rating is increasingly critical or generous or indifferent
     does their rating trend change? if so how helps build - persona signal

'''
# Step 1 — sort each user's reviews by time
df = df.sort_values(['user_id', 'timestamp'])

# Step 2 — assign a review sequence number per user (1st review, 2nd review, etc.)
df['review_seq'] = df.groupby('user_id').cumcount() + 1

# Step 3 — for each user, compute the slope of their rating over time
# a positive slope = they rate higher over time
# a negative slope = they become more critical over time
# near zero = consistent rater

def rating_slope(group):
    if len(group) < 5:  # need enough reviews to detect a trend
        return np.nan
    x = group['review_seq'].values
    y = group['rating'].values
    slope = np.polyfit(x, y, 1)[0]  # linear fit, take the slope
    return slope

user_slopes = df.groupby('user_id').apply(rating_slope).reset_index()
user_slopes.columns = ['user_id', 'rating_slope']

# Step 4 — look at the distribution of slopes across all users
print(user_slopes['rating_slope'].describe())

# Step 5 — classify users by their rating trend
def classify_trend(slope):
    if pd.isna(slope):
        return 'insufficient_data'
    elif slope > 0.05:
        return 'increasingly_generous'
    elif slope < -0.05:
        return 'increasingly_critical'
    else:
        return 'consistent'

user_slopes['trend'] = user_slopes['rating_slope'].apply(classify_trend)
print(user_slopes['trend'].value_counts())

count    1.620000e+03
mean    -1.484943e-02
std      2.539332e-01
min     -1.200000e+00
25%     -8.571429e-02
50%     -1.321078e-16
75%      5.714286e-02
max      1.100000e+00
Name: rating_slope, dtype: float64
trend
insufficient_data        630366
consistent                  734
increasingly_critical       475
increasingly_generous       411
Name: count, dtype: int64

In [14]:
# inspect one specific user's rating journey
sample_user = df[df['user_id'] == df['user_id'].iloc[129]]
display(sample_user[['timestamp', 'rating','review_seq', 'text']].to_string())

"                      timestamp  rating  review_seq                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             text\n242833  2016-07-04 20:31:23.000       5           1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                I'm still using this so I'll update the review as I learn more.  It seems good if you have sensitive skin for removing dead skin.\n242832  2016-07-04 20:42:49.000       5           2  I am prone to a certain type of infection (I’ll try not to give too much info on what kind of infections that I get), that my doctor told me that acidophilus is really good at preventing. As such, over the past several years I have taken it with great success, and can definitely tell when I stop taking it. I started noticing that a lot of probiotics have this acidophilus in it. I wanted to see if I took these probiotics if this would also help prevent me from getting the infection. I have been taking this for a little while now, and so far so good. Plus, I am really happy that it has a lot of other stuff that is really good for me that will help with my digestion and my immune system. It should be interesting to take this throughout the winter and see how that effects things. While I did receive this product at a discount, I do think it’s pretty reasonably priced, and would definitely purchase these in the future."

In [15]:
# Check a 30 reviews by myself to see if whats there is really material to build a case file on a reviewer 

import textwrap

def profile_user(df, user_id=None, min_reviews=30):
    """
    Pull one user's full review history and print it as a readable story.
    If no user_id given, randomly picks a user with min_reviews+ reviews.
    """
    
    # filter to viable users
    user_counts = df.groupby('user_id').size()
    viable_users = user_counts[user_counts >= min_reviews].index.tolist()
    
    if len(viable_users) == 0:
        print(f"No users with {min_reviews}+ reviews found.")
        return None
    
    # pick a user
    if user_id is None:
        user_id = pd.Series(viable_users).sample(1).iloc[0]
        print(f"Randomly selected user: {user_id}\n")
    elif user_id not in viable_users:
        actual_count = user_counts.get(user_id, 0)
        print(f"User {user_id} only has {actual_count} reviews. Try another.")
        return None

    # pull their reviews, sorted by time
    user_df = df[df['user_id'] == user_id].sort_values('timestamp').reset_index(drop=True)
    
    # ── HEADER ──────────────────────────────────────────────
    print("=" * 65)
    print(f"USER PROFILE: {user_id}")
    print("=" * 65)
    
    # ── QUICK STATS ─────────────────────────────────────────
    avg_rating   = user_df['rating'].mean()
    rating_std   = user_df['rating'].std()
    avg_length   = user_df['text'].str.split().str.len().mean()
    rating_dist  = user_df['rating'].value_counts().sort_index().to_dict()
    
    print(f"\n QUICK STATS")
    print(f"   Total reviews   : {len(user_df)}")
    print(f"   Avg rating      : {avg_rating:.2f}   (std: {rating_std:.2f})")
    print(f"   Avg review length: {avg_length:.0f} words")
    print(f"   Rating breakdown: {rating_dist}")
    
    # ── RATING TREND ────────────────────────────────────────
    first_half = user_df.iloc[:len(user_df)//2]['rating'].mean()
    second_half = user_df.iloc[len(user_df)//2:]['rating'].mean()
    trend = "↑ more generous over time" if second_half > first_half + 0.2 \
            else "↓ more critical over time" if second_half < first_half - 0.2 \
            else "→ consistent rater"
    print(f"   Rating trend    : {trend}  (early avg: {first_half:.2f} → late avg: {second_half:.2f})")
    
    # ── CATEGORIES ──────────────────────────────────────────
    if 'category' in user_df.columns:
        top_cats = user_df['category'].value_counts().head(5).to_dict()
        print(f"\n🗂  TOP CATEGORIES")
        for cat, count in top_cats.items():
            print(f"   {cat:<35} {count} reviews")
    
    # ── FULL REVIEW HISTORY ─────────────────────────────────
    print(f"\n📝 FULL REVIEW HISTORY  (oldest → newest)")
    print("-" * 65)
    
    for i, row in user_df.iterrows():
        # convert unix timestamp to readable date
        try:
            date = pd.to_datetime(row['timestamp'], unit='s').strftime('%b %Y')
        except:
            date = "Unknown date"
        
        stars     = "⭐" * int(row['rating'])
        title   = row.get('title', '')
        review    = row.get('text', '')
        word_count = len(str(review).split())
        
        print(f"\n[{i+1}]  {date}  |  {stars} ({int(row['rating'])}/5)  |  {word_count} words")
        
        if title:
            print(f"     Headline : {title}")
        
        # wrap the review text so it's readable
        wrapped = textwrap.fill(str(review), width=60, initial_indent="     ", subsequent_indent="     ")
        print(wrapped)
        print()
    
    print("=" * 65)
    print("ASK YOURSELF:")
    print("  1. Can I describe this person in 3 sentences?")
    print("  2. Do they have a consistent complaint or praise pattern?")
    print("  3. Does their writing style feel distinctive?")
    print("  4. Would I recognise their review if I saw it without a name?")
    print("=" * 65)
    
    return user_df

In [16]:

"""
if you go through this review below you will see that you should be able to build a case file on the reviewer 
eg shes a woman, she loves body products , lives in the desert area , has a dry skin problem ,
doesnt give 5 easily, gives 4 mostly rating wise 
"""
# random user with 30+ reviews
#user_history = profile_user(df)
# or target a specific user you already found
user_history = profile_user(df, user_id='AHBWH2LBU3NFLD46GKJKIBAHKXEQ')

# or lower the bar for testing
#user_history = profile_user(df, min_reviews=20)

=================================================================
USER PROFILE: AHBWH2LBU3NFLD46GKJKIBAHKXEQ
=================================================================

 QUICK STATS
   Total reviews   : 39
   Avg rating      : 4.05   (std: 1.00)
   Avg review length: 104 words
   Rating breakdown: {1: 1, 2: 3, 3: 3, 4: 18, 5: 14}
   Rating trend    : ↑ more generous over time  (early avg: 3.89 → late avg: 4.20)

📝 FULL REVIEW HISTORY  (oldest → newest)
-----------------------------------------------------------------

[1]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  237 words
     Headline : Good alternative to travel emery boards
     I try to avoid using traditional files and emery boards
     on my nails. I take a lot of medications that make my
     nails weak and brittle, and any surface that's too
     abrasive wreaks havoc on my fingertips. I can't carry a
     full size glass nail file with me everywhere, so I was
     on the hunt for a travel sized file that could fit in
     my pocket, wallet, or purse. When these came up, I
     thought I'd give them a shot. The pros are the files
     are a great size, they're packaged well, and I see them
     lasting for awhile. The case they come in is a nice
     touch, and I enjoyed the fact there were two so I could
     have a spare. They're pretty to look at, if that
     matters to you. They'd make great little stocking
     stuffers or gifts. There were a few con's to the files,
     but nothing too major. The abrasive side is only on one
     side of the file. I prefer to have options on the level
     of abrasiveness, so this was a little disappointing. In
     addition, the abrasive side didn't do all that great a
     job filing down my nails. It will do in a pinch, and
     it's not my favorite file, but for emergency use, it
     will do. If you need a glass file for travel purposes,
     this is the best option I have found so far, despite
     the minor drawbacks.


[2]  Unknown date  |  ⭐⭐⭐ (3/5)  |  124 words
     Headline : Flimsy curlers that rip easy
     I was intrigued by these spiral curlers when I saw
     them. I've used foam rollers occasionally in the past
     with fair results, so I thought these might work as
     well. These do curl, but they aren't great. First of
     all, these take some practice to get in. Take small
     strands of hair, or you will cause tangling. I
     recommend doing this after a shower. I left mine in
     overnight. They were easy to remove and didn't cause
     any pain. The curls were a bit... Overwhelming. It was
     an 80's nightmare, actually. To top it off, the curlers
     didn't hold up well, either, and most of them had holes
     and tore after one use. This probably won't be a curler
     set I'll be using again.


[3]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  75 words
     Headline : Good emery boards at a bargain price
     It's embarrassing how many files and emery boards I
     misplace. This set has allowed me to buy what I need
     without breaking the bank. The boards are thick, file
     well, and have lasted well with normal wear and tear.
     They don't bend easy and file corners and edges
     quickly. Considering how many files come in a pack,
     this really is a great value. You have plenty to keep
     on hand and several left to share.


[4]  Unknown date  |  ⭐ (1/5)  |  90 words
     Headline : Spoiled hand wipes
     I had high hopes for these hand sanitizing wipes. I've
     been trying to avoid alcohol hand sanitizers because
     they have a tendency to dry my hands and make them
     bleed. I've had luck with natural hand wipes because
     they don't flare my eczema or my children's eczema.
     Every package of these hand wipes we opened smelled
     spoiled and had brown streaks that looked like mold. I
     ended up throwing away the rest of the package because
     I simply didn't feel safe using the product. I don't
     recommend this at all.


[5]  Unknown date  |  ⭐⭐ (2/5)  |  100 words
     Headline : Ick
     I've used sugar scrubs before in the bath, on my face,
     and on my hands. I've also used used other items from
     this brand before. This scrub, however, makes me
     nauseous. The scrub doesn't feel moisturizing at all.
     It leaves an oily, unpleasant film on my hands. I got
     the cherry scent, but it doesn't smell anything like
     cherry blossoms. It just smells sickly and artificial.
     Maybe I got a bad batch. I couldn't stand to use this.
     After three times, I had to throw it out. The smell was
     making me sick to my stomach. I can't recommend it.


[6]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  120 words
     Headline : A decent peel that softens rough skin
     I struggle with dry feet in this desert climate, so I
     thought I'd try a foot peel. The booties fit well. I am
     a size 9 in women's shoes. They're sheer enough to not
     feel binding, but thick enough to hold the solution. It
     was a little hard to position the tape to keep the
     liquid from spilling, so I had to keep repositioning
     it. The solution smelled nice and washed clean after
     the treatment. The peeling started about a week after
     wearing. At this time, be sure to gently exfoliate and
     moisturize. DON'T peel the skin. You could hurt
     yourself. Overall, I did notice a difference and my
     feet did feel softer. I'll be doing the second
     treatment soon.


[7]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  66 words
     Headline : A gentle mask that softened my skin.
     My skin can sometimes flare with dryness and redness.
     This mask was able to reduce both in one application.
     The solution is mild and gentle enough that it didn't
     sting even my sensitive skin. The fragrance wasn't too
     strong and the mask was thick, but not too heavy
     through the treatment. It left my face feeling
     refreshed and relaxed. I wish I had another on hand.


[8]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  82 words
     Headline : They helped my dry and irritated skin
     These masks have done wonders to help with some painful
     dryness and irritation I had on my nose and cheeks. The
     masks are thick enough to stretch and hold all the
     solution required for an effective treatment. They
     moisturize well and left my skin feeling soft and
     hydrated. They are a bit more on the expensive side,
     but considering how much damage these helped, I felt
     they were a good value for the order. I truly believe
     they've improved my skin's health.


[9]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  95 words
     Headline : Seems to be a bit drying
     I have used several masks before, but never a mud mask.
     This mask is one I may need to adjust to a bit. Unlike
     pa kaged sheet masks, this mask doesn't feel
     moisturizing. It feels drying and thick through
     treatment. My skin feels soft once I was the mask off,
     but I find need to use an oil free moisturizer to
     restore the balance to my skin. The mask does smell
     decent, though, and it is packaged in a feminine,
     attractive box. I just don't know if this composition
     is right for my skin type.


[10]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  85 words
     Headline : Seems to be helping
     I have combination skin that's sensitive, oily with
     patches of dryness, and is prone to adult acne. This
     cream seems to be helping reduce some of the irritation
     and redness. I found that if I used too much, it would
     feel too thick and greasy on my skin, so a little does
     go a long way. The scent is light, the ingredients
     appear to be mild, and so far, this hasn't caused any
     flares. Overall, it seems to be a useful product for
     combination skin.


[11]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  62 words
     Headline : A good selection of easy to use decals
     These decals lend a nice touch to at home manicures.
     They're colorful and you get a big selection with your
     order. They peel off easy with tweezers and stick well
     to the nail bed. After sealing with a top coat, they
     don't peel or curl. They are durable and an easy way to
     spruce up what would otherwise be a plain look.


[12]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  80 words
     Headline : A great addition to homemade soaps and bath products
     At first I didn't know what to think of these buds.
     When they arrive, they honestly stink. Once I was able
     to separate them and use them individually in homemade
     bath bombs, though, the smell improved and really took
     off. It seemed that the process of rehydrating the
     flowers is what made the smell improve. They did make a
     nice addition to the bath products and the final result
     was a natural, fragrant bath bomb that smelled fresh
     and clean.


[13]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  88 words
     Headline : A cute way to keep sanitizers close
     These are actually adorable and great to have on hand!
     With the need for hand sanitizers, I've found these
     work well at holding what I need and keeping sanitizer
     available and handy. These clip securely to my purse
     and haven't leaked yet. They are easy to fill and the
     tops screw on securely. Regular hand sanitizers squeeze
     out easily, and I've even found that thin hand lotions
     work great too. I've cleaned a few out with soap and
     water and let them air dry. No issues so far!


[14]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  143 words
     Headline : Works great, but disappointing value
     I have a love/hate feeling about this product. To
     start, this does work. It really does. I was hit with a
     terrible sinus infection that wouldn't clear and left
     me stuffy to no end. This package poured in a bath
     helped alleviate the muscle soreness I was feeling from
     just feeling sick AND helped clear the congestion. The
     solution poured out thick, but easily dispersed in the
     bath, and as long as the water stayed warm, the scent
     continued to keep my sinuses open. Despite the fact
     that this worked so well, I HATE the fact that you only
     get one treatment per packet. I was left wishing j had
     another two or three over the course of the week to
     help me further. As far as value, if this were made in
     a larger size, I would stand behind the product more.


[15]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  119 words
     Headline : Felt great, but I wish it came in a multiple use size
     I work behind a screen most the day and often come home
     feeling fatigued and fried. I thought this bath would
     be something interesting to try out. To start, I did
     find this relaxing and refreshing. Combined with a warm
     bath, the scent of the mixture did help alleviate the
     headache and tired feeling I had carried home. I did
     feel reset after the bath. Despite the fact that I felt
     good, the bath packets are for a one time use. I wish
     these would come in a larger pouch for someone like me
     who would need to use this product more often. As of
     now, this isn't a good value for me because I couldn't
     afford regular purchasing.


[16]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  102 words
     Headline : A truly comfortable bath pillow that's easy to clean
     I enjoy taking bubble baths frequently and was looking
     for a pillow that would be comfortable in my Roman tub.
     This pillow is really fantastic. The auction cups are
     so strong, and once they stick on, the pillow will stay
     put. It doesn't take much to get it stuck, either. The
     pillow is so soft and comfortable, and it supports your
     head and lower back extremely well. It's easy to clean
     with a quick blast of water and soap or a run through
     the washer. Drying is easy. Just hang it up with the
     attached hook and it drip dries no problem.


[17]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  66 words
     Headline : A conditioner that delivers on its promise
     This oil has worked well so far. It's an easy product
     to use in an early morning grooming routine. Two drops
     daily is enough to soften and condition without
     becoming too oily. At that rate, this bottle will last
     quite awhile. It smells clean and doesn't overpower at
     all. When scrubbed with soap and water, the oil rinses
     clean and doesn't leave any type of residue.


[18]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  113 words
     Headline : Seems to help soften and condition my skin
     I had been reading about the benefits of vitamin C
     serums and their effects on skin. So far the experience
     I've had has been positive. The serum is relatively
     smooth and seems to absorb well into the skin. I use a
     roller to help. It does feel a bit sticky for my
     preference at first, but that seems to dissipate after
     a bit. There isn't any unpleasant smell of irritation
     after using which is a plus considering I have
     sensitive skin. As for long term effects, it's simply
     too early to tell. I'm hopeful this will help my skin
     look healthier and feel better. For now, at least it
     feels moisturized and softer.


[19]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  82 words
     Headline : A great and safe way to remove stubborn dry skin
     These foot masks have really helped the backs and
     bottoms of my dry and cracked heels. I have found that
     using these roughly once every two weeks is enough to
     keep my feet soft and smooth. These are easy to use and
     tape securely closed. They smell pleasant and don't
     overpower with anything artificial or "perfumed". The
     booties are thick and don't leak lotion all over the
     place, either. Once the peeling process starts, just be
     sure to moisturize and GENTLY exfoliate.


[20]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  121 words
     Headline : An effective mask that's helped clear my skin
     I've used the WIS brand of masks before with great
     success. I have combination skin that tends to flare up
     with cystic acne and dry skin all at once. The
     hyaluronic acid in the WIS brand helps keep my skin
     balanced and clear. To begin, these masks are
     comfortable and thick, staying put where I need them to
     during treatment. They don't slip off or slide. The
     medication absorbscquivkly after removal and leaves my
     face feeling soft, smooth, and moisturized. Considering
     I use these three times a week, the 24 packnis the best
     value for my money. The last me for a month and a half
     without breaking the bank. For keeping clear skin on a
     budget, give these a try.


[21]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  116 words
     Headline : A set of masks for dry, flaky skin
     I just finished the entire pack of these masks and I
     have been extremely happy with the results. These masks
     are poo perfect for those of us whose skin needs that
     extra boost of hydration from the tough winter we've
     been having. These masks are so moisturizing and left
     my skin feeling soft and smooth. The masks smelled
     clean and pleasant, and there wasn't anything
     artificial or cloying in the fragrance. They felt
     light, sheer, and comfortable throughout treatment. The
     lotion that did remain once the mask was removed was
     easily absorbed with just a bit of time. Overall, for a
     mask that's mild, gentle, and healing, this set is one
     that seems to work well.


[22]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  106 words
     Headline : A beautiful roller that works well
     I've used several facial rollers before to help apply
     serums and medications in my ski care routine. This
     roller is a very good roller as far as they come. The
     device itself is actually quite beautiful and well
     made. The handle is sturdy, the stone is polished and
     smooth, and it rolls smoothly across the skin. I didn't
     have any cracks, mars, or imperfections as far as I
     could see. The only issue I encountered was my device
     has developed a bit of a squeaking as I've used it. It
     doesn't affect the performance of the product, but for
     some this may be a bit distracting.


[23]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  90 words
     Headline : A good skincare set at a good price point
     This face roller and massager is a very good option for
     relaxation and skin care. I found that the roller
     itself and the massage tool were well made and were
     sanded uniform and smooth. The set came with an
     instruction manual to educate the user on how to
     properly use the tools and maximize its benefits. I
     didn't have any issues with the tools themselves other
     than some minor squeaking of the roller while applying
     a facial serum. All in all, it's a good set for a
     fairly low cost.


[24]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  139 words
     Headline : A mask that helps keep my skin free of blemishes
     I've struggled with cystic acne for most of my teens
     through adulthood. I recently found that hyaluronic
     acid works  best to not only clear my skin, but keep it
     clear. The WIS line of skincare products has helped
     keep my skin healthy and free of breakouts for several
     months now. These masks have helped immensely. They
     tackle the breakouts at the source, while moisturizing
     my skin and not building up oils. These masks are
     lightweight and feel sheer enough to allow my skin to
     breathe. They are still thick enough to lock in
     treatment and the medication. For the price, these are
     a fantastic deal and last me for a little more than a
     month since I only use them twice a week. Overall, if
     you are like me and struggle with difficult skin, these
     are worth a try.


[25]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  104 words
     Headline : An AMAZING heating pad
     I have a tendency to develop frequent sinus headaches,
     so I ordered this mask to help the headaches that
     develop in my sinus region and behind my eyes. This
     works GREAT. It's easy to use- just plug and go. It
     heats quickly, retains the heat, and isn't too hot to
     get uncomfortable. It is the perfect weight and helps
     so much with pain relief. It feels like it will last
     for awhile and has already helped take the edge off
     several really bad headaches and eye aches. Although
     this may not have been designed as a migraine relief
     aid, it is a true lifesaver.


[26]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  109 words
     Headline : Good product, bad shipping experience
     This foaming body wash is contained in a convenient
     pump dispenser that is easy for kids to use in the
     shower and makes washing fun. The scent is nice and
     clean, and the foam is light and mild on the skin. It
     hasn't flared eczema or caused any skin irritation, so
     this is definitely a good choice for those sensitive to
     perfumes and additives. Although the wash is truly
     great and leaves a fresh feeling afterwards, the
     container really doesn't ship well. My bottle arrived
     leaking everywhere. As a result, I lost a third of the
     product. It's a disappointment, as the body wash really
     is a good soap.


[27]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  94 words
     Headline : A mild and soothing product
     I find that green tea usually works well for my skin.
     This mask was strong enough, but still gentle enough to
     help address the problems I face with my combination
     skin. I have adult acne and eczema so the green tea
     helps soothe my sensitive skin and tackle the breakouts
     at the same time. The mask smells clean and doesn't
     have any artificial or offensive perfume smell, which
     is nice. My skin felt smooth and soft after treatment.
     All in all, this works well and works naturally with
     your skin to condition and heal.


[28]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  106 words

In [17]:
# random user with 30+ reviews
user_history = profile_user(df)

Randomly selected user: AGFAOH3NMW2D7YV3QVZSTXMTSKIQ

=================================================================
USER PROFILE: AGFAOH3NMW2D7YV3QVZSTXMTSKIQ
=================================================================

 QUICK STATS
   Total reviews   : 47
   Avg rating      : 3.85   (std: 1.04)
   Avg review length: 99 words
   Rating breakdown: {1: 2, 2: 3, 3: 8, 4: 21, 5: 13}
   Rating trend    : ↓ more critical over time  (early avg: 4.17 → late avg: 3.54)

📝 FULL REVIEW HISTORY  (oldest → newest)
-----------------------------------------------------------------

[1]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  84 words
     Headline : Quick and Easy to Apply
     These were one of the easiest mask type products I have
     used.  The application process literally takes seconds.
     Peel off and place on face and they stay there.  I left
     them on for 15 minutes and could definitely tell the
     difference afterwards.  As the package describes there
     is a little residue left when you take them off which
     yu just dab in.  Over all I was pleased with the
     effect, but not pleased enough to want to pay $7 for
     just the one set.


[2]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  53 words
     Headline : Great Value WIth Good Color Options - And It Lasts!
     This set is great for anyone possibly looking to try a
     slightly different look.  12 individual, full size
     lipsticks all in fall / Halloween type colors.  For
     truer color, as with many lipsticks, several layers
     work better.  The color lasts really well even through
     eating and drinking, but comes off easily with remover!


[3]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  63 words
     Headline : Dryer Than Some Of The Other Options Out There.
     I love these easy eye treatments and have used several
     varients.  This is a little dryer than some of the
     others used and definitely pulls a little more.  The
     results are OK but I think it loses a lot from not
     having the extra moisture left to dab in when you
     remove them.  Personally I prefer them with a more gel
     type feel.


[4]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  124 words
     Headline : It Works But Is A Little Tight!
     I wear a lot of wigs for cosplay purposes and am always
     looking for anything that can make life easier.  This
     definitely helps grip the wig in place although I did
     use it with wig clips as well.  There was definitely
     less slipping around the front area, which can be an
     issue with them sliding back.  It was a little tight
     for me and I don't have a big head.  2 hours of wearing
     it and I was ready to pull it off. For short term use
     it is a nice addition to have - for if I am just going
     to be doing a quick set of pictures or a short video,
     this would never last on my head for the day though,


[5]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  81 words
     Headline : Super Cute!
     I love these headbands.  Perfect to get me in a good
     mood while I am doing my make up.  Anyone who follows
     my facebook page would know that Cat Ears are a HUGE
     part of most things I wear so these are perfect!
     Various colors are included. The grey and pink are
     definite favorites.  Would be a great present for cat
     lovers, or anyone who wants something FUN while they
     are getting ready / doing their skin care routine etc
     etc.


[6]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  74 words
     Headline : Nice Packaging and a Vibrant Color
     This lipstick is the sort that is great to pull out of
     your purse in places because it just looks super
     classy.  The color is nice and vibrant and it doesn't
     dry out your lips.  The effect is quite matte so I will
     confess I added a staying gloss over it - but purely
     for visual effect. My skin tone was failing to pull off
     the flatter red. It didn't need it for moisture.


[7]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  82 words
     Headline : Layer Up For Best Effect
     I used the copper and the white/silver to create the
     effect in the picture. I love that the color was long
     lastig and definitely shimmery.  It didn't flake off as
     some glitter based ones do.  I found the best effect
     occurred if I let a layer dry and then added more - to
     build up the shine but if I didn't wait long enough
     between layers it did get a little clumpy.  Overall a
     fun addition for the holiday / party season.


[8]  Unknown date  |  ⭐⭐⭐ (3/5)  |  53 words
     Headline : Not My Favorite
     The color on these are strong, but they feel a little
     waxy for my preference. That being said they do stain
     quite well and there was a variety of red shades which
     means there would be something for most skin types.
     Just not one I can see me using on a regular basis.


[9]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  52 words
     Headline : All About The Purple!
     These are really good purple options. The crayons make
     it easy to use for underlining the eyes. It was a
     little tricky to use as a shadow, with more being
     needed and it definitely took more work to do that, but
     as a general addition to my make up I was pleased.


[10]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  62 words
     Headline : Nice options but not too sturdy (one of the gems fell off)
     I needed a peacock clip for my vikings cosplay and this
     worked really well. Having the 3 separate pieces allows
     for lots of variety and styling options. The only
     downside is that the glue on one had completely dried
     up and the gem had fallen off in the packet. Super glue
     handled that but it did stop it from getting 5 stars.


[11]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  71 words
     Headline : Cute - but not the easiest to style!
     This wig looks super cute once you get it sorted. The
     bangs are long, and needed trimming, which is pretty
     normal for me, but this one was a little trickier to
     get adjusted correctly and I ended up using extra clips
     to secure it. Short wigs are often harder to work with
     because there are less places to hide the mistakes, but
     overall I ended up with a very cute look.


[12]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  59 words
     Headline : Convenient Individual Packets!
     These are very convenient to throw in your purse when
     you are on the go, especially with everything going on
     at the moment. Working out at just under $1 a use they
     are pretty good value for money. They don't have a
     harsh scent and they aren't drying on your skin which
     is always a plus. A good product!


[13]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  97 words
     Headline : Fabulous!
     I love magnetic lashes - they have totally changed how
     I feel about False eyelashes and I use them ALL the
     time. This set comes with two liquid liners which I
     love! The lashes stay all day with no issues at all and
     the variety of styles means you can have them looking
     more natural - or super dramatic.  The only thing I
     would say is that they say reusable - and I know people
     that do wash and reuse them but my eyes are sensitive
     and so I only use each pair for a single use.


[14]  Unknown date  |  ⭐⭐⭐ (3/5)  |  77 words
     Headline : Very Soft but not good  for longer / thciker hair.
     My daughter has thick hair which sits a couple of
     inches below her shoulders and takes forever to dry so
     I hoped these would be a good solution. Sadly although
     they are super soft, they don't absorb enough if you
     have longer / thicker hair.  My hair is shorter and
     thinner than my daughters and although it worked better
     on that - it still wasn't much better than a regular
     towel.  Very cute - but disappointing results.


[15]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  70 words
     Headline : Great Pins At A Great Price
     As someone who works with wigs a lot, having various
     color options is important to me, as these pins
     generally are only good for one use (although I have
     used these for a couple of uses before having to ditch
     them).  Having all the colors in one set is great and
     very convenient for someone like me - or if you have
     more than one hair color in the house.


[16]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  74 words
     Headline : It Definitely Works!
     I wear a lot of wigs - and am always looking for
     anything that can make them easier to wear. This
     product definitely worked, was easy to use, but I am
     not sure that it is worth the price. I have other items
     that have worked as well that weren't as expensive.  If
     this was a little cheaper though it would be fabulous
     for cosplayers that use a lot of different wigs /
     toppers.


[17]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  50 words
     Headline : It lives in my freezer!
     This has taken up permanent residence in my freezer. It
     is great when I just need a quick refresh, oh my eyes
     are tired, or I have a headache.  I have other rollers
     too but this is larger than most of them so you can hit
     more area at once.


[18]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  99 words
     Headline : Love them!
     These are great! I am a big fan of the liquid liner
     over the pens. Super easy to use and you can have
     professional looking lashes in 2 easy steps. This set
     has a nice variety of lash styles from every day to
     super dramatic which is nice. They say reusable - I
     don't reuse mine because my eyes are super sensitive so
     can't comment on that part but I have seen that lots of
     people do reuse them so it is probably personal
     preference but I couldn't say how many uses you might
     get out of each pair.


[19]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  97 words
     Headline : A Good Primer - But Heavy For Regular Use
     This is a great kit, for when you REALLY want your
     make-up to be on point. The primer gives a really great
     base and helps the foundation to look smooth and not
     crack, the ONLY downside is that for me, it doesn't
     allow my skin to breathe enough and I end up with
     breakouts if use it more than on the odd occasion which
     is a shame.  That being said a little goes a very long
     way, and on the days when I need my make up to be extra
     perfect then this gives me great results!


[20]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  46 words
     Headline : Excellent!
     These tweezers are fabulous. They grip even the
     smallest of hairs with no issues. The larger ones are
     so good that I haven't really needed the smaller ones
     (although I did try them just so that I could compare
     for the review). Very impressed! Highly recommend!


[21]  Unknown date  |  ⭐⭐ (2/5)  |  137 words
     Headline : The Rose Quartz Roller Is Nice ....
     The Rose Quartz roller that comes with this is really
     nice., and I use it ALL the time. The micro needling
     kit - not so much. I am assuming that these are
     supposed to be one use and disposable (as there are NO
     options for changing/replacing the needle heads) -
     which could be a good thing in that at least you know
     for a fact it's clean. I read a lot about this and
     generally feel that it should be left to professionals!
     There is no way to tell what shape the little needles
     are on this (which from reading is pretty important),
     and there are LOTS of things that can go wrong. I am
     all about doing stuff at home - but I personally don't
     think a disposable micro needling kit is one of those
     things.


[22]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  81 words
     Headline : Worth The Money!
     I have always been a fan of black eyeliner. I never
     considered using anything else until now. I LOVE how
     bright this makes my eyes look. The pencil can be used
     in various ways but by far my favorite is to use it as
     an eyeliner. It's amazing quality, and although a
     little more expensive than I would have looked at
     before trying - now I'm a convert! I can't believe it
     took me so long to give it a try!


[23]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  81 words
     Headline : Stunning In Pictures
     This is an absolutely stunning piece that photographs
     beautifully!  If you try and use it in more of a
     headband style it is a little pinching but it sites
     beautifully on top like a crown and looks way more
     expensive than it is.  Perfect for brides, cosplay, or
     any time you need a fabulous crown! This is a Tiara
     style - not a complete ring - which makes it much
     easier for styling purposes. A wonderful piece and a
     new favorite!


[24]  Unknown date  |  ⭐ (1/5)  |  72 words
     Headline : Too big for my little mouth!
     This was just too big for my mouth - no matter how much
     I squished it.  I can't really say as to whether it
     would work or not because I couldn't really try it and
     nobody else in the house thought it looked like
     something they wanted to try. I am an adult - so feel
     that this should have been able to be small enough for
     everyone- but it was not!


[25]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  87 words
     Headline : Like The Tea Bag Trick!
     In England when I was younger, if your eyes were tired
     or puffy my mum would always tell me to put used tea
     bags on them. This is what these patches are like! 15
     minutes wear and your eyes really do feel better -
     especially if you are suffering because of too much
     screen time. Don't be put off by the fact that the
     instructions aren't in English. Just take out a new
     pair, place on closed eyes for 15 minutes, and discard.
     You won't regret it!


[26]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  99 words
     Headline : Such A Cute Idea!
     I LOVE Scrunchies - I am so excited that they are
     making a comeback and this is such a fun way to store
     them. I mean yes it is a little annoying if the one you
     want happens to be at the bottom - but not really a big
     deal. I think it's great that this comes with 8
     scrunchies already - that in itself pretty much pays
     for it - but you can add lots more! If you are a
     scrunchie person then this is for you. I have mine on
     my dressing table and I love it!


[27]  Unknown date  |  ⭐⭐⭐ (3/5)  |  139 words
     Headline : Good not Great
     This definitely moisturizes, there is no question about
     that. I found that because of the texture (it's almost
     whipped) that you end up needing to use more product
     than with many of the options. Not sure that my skin
     would be stressed - but it definitely goes through a
     lot with the amount of make-up I put on it.  It is
     supposed to be fragrance-free and there's definitely
     not a perfume element - but maybe there should be, It
     smelled weird to me. I can't put my finger on what it
     was exactly just that I didn't really like it, but I
     can be picky over scents so that might just be me.
     Overall it was good - but not great - but also it's a
     mid-range rather than a higher price product which
     should be taken into account.


[28]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  110 words
     Headline : Beautiful But Heavy & Not The Easiest To Wear
     This crown is absolutely gorgeous. The detailing is
     really lovely and it sparkles beautifully. It comes
     packaged in a lovely blue box which conveniently could
     double as storage for it.  As with many complete circle
     crowns the wear and fit is an issue. This is definitely
     on the smaller size - and it is a little tricky to get
     it pinned in an acceptable position. The other note I
     have is that it is really heavy, on the plus side it
     doesn't feel like it will fall apart with the slightest
     movement - but between that and the size - sadly it
     probably won't become one of my regular pieces.


[29]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  65 words
     Headline : A Little Hard - But Great Color!
     This set of lip liners are a great set of Reds - and
     the colors are great. The only problem for me was that
     they are a little hard which means sometimes they are a
     little scratchy and harder to get the perfect lines.
     For the price though you are getting a good selection
     with pretty much any shade of Red liner you could need.


[30]  Unknown date  |  ⭐⭐⭐ (3/5)  |  90 words
     Headline : Definitely Not The Best!
     I have lots of crowns that I use for various costumes.
     Full circle crowns are always harder to work with but
     this was made extra tricky from the fact that there is
     a very badly placed seam at what should be the front.
     Although it is sparkly - it is definitely not as well
     made as many of the others that I have that have been
     in the same price range. It is described as "Rose Gold"
     but it is definitely more "Gold Gold" in reality.
     Overall lackluster and disappointing.


[31]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  72 words
     Headline : Cute Color - Bangs Are A Little Long
     This is a cute pink wig. The short waves make it pretty
     easy to wear but the bangs on it were super long and I
     had to trim them quite a lot to get it to look good. It
     is comfortable and would be great for cosplay but I
     couldn't quite get it adjusted enough for it to become
     one of my gotos that I would actually wear as a daily
     option.


[32]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  59 words
     Headline : A Nice Vibrant Red!
     This lipstick is a really nice vibrant red color and
     stays on well without being drying. It did have a
     little bit of an unusual taste, not unpleasant, but
     enough that I noticed it hence the 4 stars. Other than
     that the coverage was great, it didn't smudge, and it
     looked fabulous. I will definitely be wearing it often.


[33]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  124 words
     Headline : Great Set - Especially For Eye MakeUp
     I use a LOT of makeup brushes - and yes part of that is
     because I GET a lot of makeup brushes and I am not a
     fan of cleaning them but it also means that I try out a
     lot of different brands.  These worked REALLY well for
     my trickier eye makeup looks. They are soft but they
     hold the color well and disperse it evenly without much
     effort. The brush cleaner is a nice addition but being
     honest I probably won't use it. I do have an automatic
     brush cleaner if I need one and that will always be my
     go to.  For beginners or those looking to get a but
     more technical these are a great brush choice in my
     opinion!


[34]  Unknown date  |  ⭐⭐⭐⭐⭐ (5/5)  |  104 words
     Headline : Perfect For Wigs!
     I have a lot of wigs and crowns and this is the perfect
     thing to use for styling them! This is the second one I
     have, and this one allows for earrings to be placed as
     well (which I personally don't use but I can see how it
     would be handy for a store display, or if you were
     taking pictures for selling jewelry). I have named her
     Rachel, to go with Monica that I already have, and she
     is definitely a talking point. Great quality, and
     whilst not the sort of thing everyone would need,
     cosplayers I think would find her very useful!


[35]  Unknown date  |  ⭐⭐⭐⭐ (4/5)  |  137 words
     Headline : It Has All The Essentials
     I am not a big traveler but this definitely has the
     essentials all ready to go in an FDA-approved clear
     bag. The items are decent quality but probably the most
     useful things are the bag it all comes in, and a little
     card that tells you all the things that you should be
     wiping down, a couple of which I hadn't thought of. I
     also hadn't thought of taking my own pillowcase before
     but having seen that it makes total sense. Yes, you
     could probably get all the things in it a little

### 4. Review text signals
The text is where persona lives. we need to know if there's enough text per user to extract writing style.

In [18]:
# Review length distribution
df['text'].str.split().str.len().describe()

count    701316.000000
mean         32.760465
std          45.976779
min           0.000000
25%           8.000000
50%          19.000000
75%          40.000000
max        2585.000000
Name: text, dtype: float64

In [19]:
#Empty / very short reviews
# we have to filter this out cause the review is too short

df[df['text'].str.len() < 20].shape[0]

74629

In [20]:
# Avg text length per user
avg_text_per_user = df.groupby('user_id')['text'].apply(lambda x: x.str.len().mean())

In [21]:
display(avg_text_per_user)

user_id
AE222BBOVZIF42YOOPNBXL4UUMYA     52.0
AE222FP7YRNFCEQ2W3ZDIGMSYTLQ     44.0
AE222X475JC6ONXMIKZDFGQ7IAUA     14.0
AE222Y4WTST6BUZ4J5Y2H6QMBITQ    184.0
AE2232TEZOEWQLAFEX2NA6VBGMYQ     19.0
                                ...
AHZZYVEU6QFMPFZ2HJUWR22SNK4A     11.0
AHZZZAK24AJ3JNBDUZJGHHWSRVAA    226.0
AHZZZJP24QUSB5XWW6MAXYBZZZSQ     33.0
AHZZZL7YQJA3RSA6PYK3WMFACYIQ    114.0
AHZZZSOTVOVACVK2WWXL4ITEAPIA     17.0
Name: text, Length: 631986, dtype: float64

In [22]:
#print(avg_text_per_user.value_counts())

In [23]:
# Verified purchase flag

df['verified_purchase'].value_counts()
# prefer verified = True

verified_purchase
True     634969
False     66559
Name: count, dtype: int64

## Combined function to get the rich-review data
this function uses the data exploration techniques above to get the rich reviews and also cleans the data

In [24]:
import pandas as pd

def clean_amazon_reviews(df, 
                          min_reviews=20, 
                          min_word_count=30,
                          verified_only=True):
    """
    Full cleaning pipeline for Amazon Reviews dataset.
    Returns a clean dataframe of viable users ready for persona building.
    """
    
    print("=" * 60)
    print("AMAZON REVIEWS — CLEANING PIPELINE")
    print("=" * 60)
    print(f"\n▶ Starting shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
    
    # ── STEP 1: DROP DUPLICATE ROWS ─────────────────────────
    before = len(df)
    df = df.drop_duplicates()
    after = len(df)
    print(f"\n[1] Duplicate rows removed   : {before - after:,}")
    print(f"    Remaining                : {after:,}")
    
    # ── STEP 2: DROP DUPLICATE COLUMNS ──────────────────────
    before_cols = df.shape[1]
    df = df.loc[:, ~df.columns.duplicated()]
    after_cols = df.shape[1]
    print(f"\n[2] Duplicate columns removed: {before_cols - after_cols}")
    print(f"    Remaining columns        : {list(df.columns)}")
    
    # ── STEP 3: REQUIRE CRITICAL COLUMNS ────────────────────
    critical_cols = ['user_id', 'rating', 'text']
    missing_cols  = [c for c in critical_cols if c not in df.columns]
    
    if missing_cols:
        print(f"\n❌ STOPPING — missing critical columns: {missing_cols}")
        print(f"   Your dataset has: {list(df.columns)}")
        return None
    
    before = len(df)
    df = df.dropna(subset=critical_cols)
    after = len(df)
    print(f"\n[3] Rows dropped (missing critical fields): {before - after:,}")
    print(f"    Remaining                              : {after:,}")
    
    # ── STEP 4: CLEAN REVIEW TEXT ───────────────────────────
    # strip whitespace
    df['text'] = df['text'].astype(str).str.strip()
    
    # remove placeholder text that slips through
    placeholders = ['n/a', 'na', 'none', 'null', '.', '-', 'no review']
    before = len(df)
    df = df[~df['text'].str.lower().isin(placeholders)]
    
    # remove very short reviews (below min_word_count)
    df['word_count'] = df['text'].str.split().str.len()
    df = df[df['word_count'] >= min_word_count]
    after = len(df)
    print(f"\n[4] Rows dropped (empty / short reviews) : {before - after:,}")
    print(f"    Min word count threshold             : {min_word_count} words")
    print(f"    Remaining                            : {after:,}")
    
    # ── STEP 5: VERIFIED PURCHASES ONLY ─────────────────────
    if verified_only and 'verified_purchase' in df.columns:
        before = len(df)
        df = df[df['verified_purchase'] == True]
        after = len(df)
        print(f"\n[5] Rows dropped (unverified purchases)  : {before - after:,}")
        print(f"    Remaining                            : {after:,}")
    elif 'verified_purchase' not in df.columns:
        print(f"\n[5] Skipped — 'verified' column not found in dataset")
    
    # ── STEP 6: VALID RATINGS ONLY ──────────────────────────
    before = len(df)
    df = df[df['rating'].between(1, 5)]
    after = len(df)
    print(f"\n[6] Rows dropped (invalid ratings)       : {before - after:,}")
    print(f"    Remaining                            : {after:,}")
    
    # ── STEP 7: FILTER TO USERS WITH 20+ REVIEWS ────────────
    before = len(df)
    user_counts  = df.groupby('user_id').size()
    viable_users = user_counts[user_counts >= min_reviews].index
    df = df[df['user_id'].isin(viable_users)]
    after = len(df)
    dropped_users = len(user_counts) - len(viable_users)
    print(f"\n[7] Users dropped (< {min_reviews} reviews)          : {dropped_users:,}")
    print(f"    Viable users remaining               : {len(viable_users):,}")
    print(f"    Rows remaining                       : {after:,}")
    
    # ── STEP 8: SORT BY USER + TIME ─────────────────────────
    if 'timestamp' in df.columns:
        df = df.sort_values(['user_id', 'timestamp']).reset_index(drop=True)
        print(f"\n[8] Sorted by user_id + timestamp ✓")
    else:
        df = df.sort_values('user_id').reset_index(drop=True)
        print(f"\n[8] Sorted by user_id (no timestamp found) ✓")
    
    # ── FINAL SUMMARY ───────────────────────────────────────
    print(f"\n{'=' * 60}")
    print(f"✅ CLEAN DATASET READY")
    print(f"{'=' * 60}")
    print(f"   Final shape      : {df.shape[0]:,} rows × {df.shape[1]} columns")
    print(f"   Unique users     : {df['user_id'].nunique():,}")
    print(f"   Avg reviews/user : {df.groupby('user_id').size().mean():.1f}")
    print(f"   Avg word count   : {df['word_count'].mean():.0f} words")
    print(f"   Rating breakdown : {df['rating'].value_counts().sort_index().to_dict()}")
    print(f"{'=' * 60}\n")
    
    return df

In [25]:
rich_df = clean_amazon_reviews(df,min_reviews=10)

============================================================
AMAZON REVIEWS — CLEANING PIPELINE
============================================================

▶ Starting shape: 701,528 rows × 11 columns

[1] Duplicate rows removed   : 0
    Remaining                : 701,528

[2] Duplicate columns removed: 0
    Remaining columns        : ['rating', 'title', 'text', 'images', 'asin', 'parent_asin', 'user_id', 'timestamp', 'helpful_vote', 'verified_purchase', 'review_seq']

[3] Rows dropped (missing critical fields): 212
    Remaining                              : 701,316

[4] Rows dropped (empty / short reviews) : 456,456
    Min word count threshold             : 30 words
    Remaining                            : 244,860

[5] Rows dropped (unverified purchases)  : 41,244
    Remaining                            : 203,616

[6] Rows dropped (invalid ratings)       : 0
    Remaining                            : 203,616

[7] Users dropped (< 10 reviews)          : 192,293
    Viable users remaining               : 7
    Rows remaining                       : 100

[8] Sorted by user_id + timestamp ✓

============================================================
✅ CLEAN DATASET READY
============================================================
   Final shape      : 100 rows × 12 columns
   Unique users     : 7
   Avg reviews/user : 14.3
   Avg word count   : 77 words
   Rating breakdown : {2: 3, 3: 2, 4: 10, 5: 85}
============================================================

In [26]:
rich_df.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,review_seq,word_count
0,4,Doesn't leave marks on clothes!,This makeup is crazy. It comes out of the bot...,[],B07VNQ4G13,B07VNQ4G13,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,2019-08-29 21:11:38.664,0,True,1,158
1,5,Colour Changing Foundation,This foundation is like no other foundation. ...,[],B07VML1QZC,B07VML1QZC,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,2019-09-27 15:08:38.780,0,True,2,97
2,5,Immediately see the difference...,This under eye cream is amazing. The first ti...,[],B07X1PH59J,B07X1PH59J,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,2019-10-10 11:17:52.243,0,True,3,137
3,4,Makeup concealer,"This 3 pack of cream concealer is well, very c...",[],B07XNYVBY5,B07XNYVBY5,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,2019-10-31 07:16:34.158,0,True,4,132
4,4,Lightweight Primer,I was surprised by how lightweight this primer...,[],B0828LCHWC,B0828LCHWC,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,2019-12-23 06:14:41.575,0,True,5,124

In [27]:
rich_df.to_csv('rich_users.csv', index=False)

# Part 2 Build a Persona

## Persona style

In [28]:

import re

# ── STEP 1: STATISTICAL PERSONA (no LLM needed) ─────────────────

def extract_statistical_persona(df):
    """
    Extracts measurable traits per user from their review history.
    No LLM call yet — pure signal extraction from data.
    """

    def rating_trend(ratings):
        """slope of ratings over time — positive = more generous, negative = more critical"""
        if len(ratings) < 4:
            return 0.0
        x = np.arange(len(ratings))
        slope = np.polyfit(x, ratings, 1)[0]
        return round(float(slope), 4)

    def writing_style(texts):
        """extract fingerprint signals from review text"""
        texts = [str(t) for t in texts if len(str(t)) > 10]
        if not texts:
            return {}
        
        all_sentences = []
        all_words     = []
        openers       = []
        
        for text in texts:
            sentences = re.split(r'[.!?]+', text)
            sentences = [s.strip() for s in sentences if len(s.strip()) > 5]
            words     = text.lower().split()
            
            all_sentences.extend(sentences)
            all_words.extend(words)
            if words:
                openers.append(words[0])  # first word of each review
        
        avg_sentence_len = np.mean([len(s.split()) for s in all_sentences]) if all_sentences else 0
        vocab_richness   = len(set(all_words)) / len(all_words) if all_words else 0  # type-token ratio
        avg_review_len   = np.mean([len(t.split()) for t in texts])
        
        # is this person verbose or terse?
        verbosity = "verbose" if avg_review_len > 80 \
                    else "moderate" if avg_review_len > 40 \
                    else "terse"
        
        # most common opener words (excluding stopwords)
        stopwords = {'i', 'the', 'this', 'a', 'an', 'it', 'my', 'we', 'so'}
        meaningful_openers = [w for w in openers if w not in stopwords]
        top_opener = meaningful_openers[0] if meaningful_openers else "unknown"
        
        return {
            "avg_sentence_len"  : round(avg_sentence_len, 1),
            "vocab_richness"    : round(vocab_richness, 3),
            "avg_review_len"    : round(avg_review_len, 1),
            "verbosity"         : verbosity,
            "common_opener"     : top_opener
        }

    def complaint_signals(texts):
        """detect recurring complaint or praise patterns"""
        all_text = " ".join([str(t).lower() for t in texts])
        
        signals = {
            "mentions_price"    : bool(re.search(r'\b(price|expensive|cheap|cost|worth|value|money)\b', all_text)),
            "mentions_quality"  : bool(re.search(r'\b(quality|durable|broke|lasted|cheap|flimsy|solid)\b', all_text)),
            "mentions_shipping" : bool(re.search(r'\b(shipping|delivery|arrived|package|days|late|fast)\b', all_text)),
            "mentions_service"  : bool(re.search(r'\b(service|support|help|staff|seller|response)\b', all_text)),
            "uses_caps"         : bool(re.search(r'\b[A-Z]{3,}\b', " ".join([str(t) for t in texts]))),
            "uses_exclamation"  : " ".join([str(t) for t in texts]).count("!") > len(texts)
        }
        return signals

    def rating_profile(ratings):
        """classify this user's rating personality"""
        avg = np.mean(ratings)
        std = np.std(ratings)
        
        if avg >= 4.2:
            generosity = "generous"
        elif avg <= 2.8:
            generosity = "harsh"
        else:
            generosity = "balanced"
        
        consistency = "consistent" if std < 0.8 else "variable"
        
        return {
            "generosity"   : generosity,
            "consistency"  : consistency,
            "never_gives_5": int(5 not in ratings),
            "never_gives_1": int(1 not in ratings)
        }

    # ── AGGREGATE PER USER ───────────────────────────────────────
    rows = []

    for user_id, group in df.groupby('user_id'):
        group = group.sort_values('timestamp') if 'timestamp' in group.columns else group

        ratings  = group['rating'].tolist()
        texts    = group['text'].tolist()

        style    = writing_style(texts)
        signals  = complaint_signals(texts)
        profile  = rating_profile(ratings)

        row = {
            "user_id"      : user_id,

            # --- rating stats ---
            "review_count"    : len(ratings),
            "avg_rating"      : round(np.mean(ratings), 2),
            "rating_std"      : round(np.std(ratings), 2),
            "rating_trend"    : rating_trend(ratings),

            # --- rating profile ---
            "generosity"      : profile["generosity"],
            "consistency"     : profile["consistency"],
            "never_gives_5"   : profile["never_gives_5"],
            "never_gives_1"   : profile["never_gives_1"],

            # --- writing style ---
            "verbosity"       : style.get("verbosity"),
            "avg_review_len"  : style.get("avg_review_len"),
            "vocab_richness"  : style.get("vocab_richness"),
            "avg_sentence_len": style.get("avg_sentence_len"),
            "common_opener"   : style.get("common_opener"),

            # --- complaint / praise signals ---
            "mentions_price"  : signals["mentions_price"],
            "mentions_quality": signals["mentions_quality"],
            "mentions_shipping": signals["mentions_shipping"],
            "mentions_service": signals["mentions_service"],
            "uses_caps"       : signals["uses_caps"],
            "uses_exclamation": signals["uses_exclamation"],

            # --- sample reviews for LLM trait extraction (next step) ---
            "sample_reviews"  : texts[:5],
            "reviewed_items"  : group['asin'].tolist() if 'asin' in group.columns else []
        }
        rows.append(row)

    persona_df = pd.DataFrame(rows)
    print(f" Statistical personas extracted for {len(persona_df):,} users")
    print(f"   Columns: {list(persona_df.columns)}")
    return persona_df


# ── RUN IT ───────────────────────────────────────────────────────
persona_df_claude = extract_statistical_persona(rich_df)

 Statistical personas extracted for 7 users
   Columns: ['user_id', 'review_count', 'avg_rating', 'rating_std', 'rating_trend', 'generosity', 'consistency', 'never_gives_5', 'never_gives_1', 'verbosity', 'avg_review_len', 'vocab_richness', 'avg_sentence_len', 'common_opener', 'mentions_price', 'mentions_quality', 'mentions_shipping', 'mentions_service', 'uses_caps', 'uses_exclamation', 'sample_reviews', 'reviewed_items']

In [29]:
persona_df_claude.head()

,user_id,review_count,avg_rating,rating_std,rating_trend,generosity,consistency,never_gives_5,never_gives_1,verbosity,...,avg_sentence_len,common_opener,mentions_price,mentions_quality,mentions_shipping,mentions_service,uses_caps,uses_exclamation,sample_reviews,reviewed_items
0,AE7P3G7DWP3VVFKOK2H2PPTK2TOA,11,4.64,0.48,0.0455,generous,consistent,0,1,verbose,...,16.1,these,True,True,True,True,True,False,[This makeup is crazy. It comes out of the bo...,"[B07VNQ4G13, B07VML1QZC, B07X1PH59J, B07XNYVBY..."
1,AEYKTZXAWOPJG5MGGMKBLRJR6Q3A_2,21,4.95,0.21,0.0052,generous,consistent,0,1,moderate,...,41.9,impressive,True,True,True,False,False,False,[Impressive device. Operates on by charge on u...,"[B07WMFRDZ3, B07QYD1J5C, B07XRJC4TY, B07YSC7V2..."
2,AFR4BTNWATNG7O4SOME4XK6NNBYQ,10,4.80,0.40,0.0848,generous,consistent,0,1,moderate,...,11.8,what,False,False,True,False,True,False,[The bar is rather small..but the jasmine is o...,"[B0013EHI6G, B00CBY2W4U, B004FO8KPE, B00TJE4JU..."
3,AFSCJNRG4BAGAB37REW4XCDPE6XA,11,5.00,0.00,0.0000,generous,consistent,0,1,moderate,...,10.7,tired,True,False,False,False,False,False,[My first experience with a shaver Like this a...,"[B07RG332M3, B07QQQXZ4S, B07Q3BSDC8, B07V6BK6H..."
4,AFUBMCVI5J6G4F2RFQGTDRXLE6VQ,10,3.40,1.11,-0.0364,balanced,variable,0,1,verbose,...,11.2,fantastic,True,False,True,True,True,False,[fantastic value for fake hair. perfect color...,"[B00D93WF26, B00IJVVBG4, B089XX8C33, B08D3HBC3..."

## Prompt Building

In [30]:
def build_user_prompt(user_row, item_asin, item_title, item_description, nigerian_mode=False ):
    """
    Builds a persona-conditioned prompt for review simulation.
    Designed for Gemini API. Uses chain-of-thought before generation.
    
    Parameters:
        user_row         : one row from persona_df
        item_asin        : product ID
        item_title       : product name
        item_description : product description
        nigerian_mode    : inject Nigerian cultural conditioning layer
    """

    # ── 1. BUILD TRAIT SUMMARY ───────────────────────────────────
    # translate extracted traits into natural language descriptions
    # so the LLM gets character, not just numbers

    trait_lines = []

    # rating personality
    generosity   = user_row.get('generosity', 'balanced')
    consistency  = user_row.get('consistency', 'consistent')
    avg_rating   = user_row.get('avg_rating', 3.0)
    rating_std   = user_row.get('rating_std', 1.0)
    rating_trend = user_row.get('rating_trend', 0.0)

    trait_lines.append(f"- They are a {generosity} rater — their average rating is {avg_rating:.1f}/5")
    trait_lines.append(f"- They are {consistency} in their ratings (std dev: {rating_std:.2f})")

    if user_row.get('never_gives_5'):
        trait_lines.append("- They NEVER give 5 stars — even for things they like")
    if user_row.get('never_gives_1'):
        trait_lines.append("- They have never given 1 star — even when disappointed")
    if rating_trend > 0.05:
        trait_lines.append("- Their ratings have been trending upward — they are becoming more generous over time")
    elif rating_trend < -0.05:
        trait_lines.append("- Their ratings have been trending downward — they are becoming more critical over time")

    # writing style
    verbosity        = user_row.get('verbosity', 'moderate')
    avg_review_len   = int(user_row.get('avg_review_len', 50))
    vocab_richness   = user_row.get('vocab_richness', 0.5)
    avg_sentence_len = user_row.get('avg_sentence_len', 15)
    common_opener    = user_row.get('common_opener', '')

    trait_lines.append(f"- Writing style: {verbosity} — they write around {avg_review_len} words per review")
    trait_lines.append(f"- Sentence length: avg {avg_sentence_len:.0f} words per sentence")
    if vocab_richness > 0.7:
        trait_lines.append("- They use rich, varied vocabulary — rarely repeat the same words")
    elif vocab_richness < 0.4:
        trait_lines.append("- They use simple, repetitive vocabulary — plain everyday language")
    if common_opener:
        trait_lines.append(f"- They often start their reviews with words like: '{common_opener}'")

    # complaint / praise signals
    if user_row.get('mentions_price'):
        trait_lines.append("- Price and value for money is a recurring theme in their reviews")
    if user_row.get('mentions_quality'):
        trait_lines.append("- Product quality and durability is something they always comment on")
    if user_row.get('mentions_shipping'):
        trait_lines.append("- They frequently mention shipping speed and delivery experience")
    if user_row.get('mentions_service'):
        trait_lines.append("- Customer service experience often appears in their reviews")
    if user_row.get('uses_exclamation'):
        trait_lines.append("- They use exclamation marks frequently — expressive and emotional tone")
    if user_row.get('uses_caps'):
        trait_lines.append("- They occasionally use ALL CAPS for emphasis")

    traits_block = "\n".join(trait_lines)

    # ── 2. FORMAT SAMPLE REVIEWS ─────────────────────────────────
    samples = user_row.get('sample_reviews', [])
    if samples:
        sample_block = "\n\n".join([
            f"  Past review {i+1}:\n  \"{str(r).strip()}\""
            for i, r in enumerate(samples[:4])  # max 4 samples
        ])
    else:
        sample_block = "  No sample reviews available."

    # ── 3. NIGERIAN CONDITIONING LAYER ───────────────────────────
    nigerian_block = ""
    if nigerian_mode:
        nigerian_block = """
IMPORTANT CULTURAL CONTEXT:
This reviewer is Nigerian. Their review should naturally reflect Nigerian consumer behaviour:
- They are price-conscious and often compare value to local alternatives
- They may reference familiar Nigerian brands, experiences, or comparisons ("like the ones in Shoprite", "better than what you find for Ikeja")
- They may code-switch lightly — mixing standard English with Pidgin phrases naturally (e.g. "e good sha", "I no go lie", "the thing dey work")
- Do NOT force Pidgin on every sentence — use it sparingly and naturally, the way an educated Nigerian would
- They may mention community or family context ("my whole family", "my colleagues at work")
- Scepticism about product claims is common — they may note what surprised them vs expectation
"""

    # ── 4. RATING ANCHOR ─────────────────────────────────────────
    # give the LLM a statistical prior so rating prediction stays
    # close to this user's actual behaviour — reduces RMSE significantly
    low  = max(1, round(avg_rating - rating_std))
    high = min(5, round(avg_rating + rating_std))
    rating_anchor = f"Based on their history, their rating will most likely fall between {low} and {high} stars."

    # ── 5. ASSEMBLE THE FULL PROMPT ──────────────────────────────
    prompt = f"""You are simulating the review behaviour of a specific, real Amazon user.
Your job is NOT to write a good review — your job is to write the review THIS SPECIFIC PERSON would write.
Stay in character throughout. Do not default to generic reviewer behaviour.

═══════════════════════════════════════════
WHO THIS PERSON IS
═══════════════════════════════════════════
{traits_block}

═══════════════════════════════════════════
SAMPLES OF HOW THEY ACTUALLY WRITE
═══════════════════════════════════════════
{sample_block}
{nigerian_block}
═══════════════════════════════════════════
THE PRODUCT THEY ARE REVIEWING (UNSEEN)
═══════════════════════════════════════════
Product title      : {item_title}
Product ID (ASIN)  : {item_asin}
Product description: {item_description}

═══════════════════════════════════════════
INSTRUCTIONS
═══════════════════════════════════════════
Before writing the review, reason briefly:
- What would this person notice about this product given their traits?
- What would they likely complain about or praise?
- What rating does their history suggest they would give?

{rating_anchor}

Then produce your output in EXACTLY this format — nothing before, nothing after:

REASONING: [2-3 sentences of internal reasoning about this user and this product]
RATING: [single integer 1-5]
TITLE: [short review headline in their voice]
REVIEW: [full review text in their voice and style]
""".strip()

    return prompt

In [31]:
# use the kaggle secret enviroment to secure my api key 
from kaggle_secrets import UserSecretsClient

GOOGLE_API_KEY = UserSecretsClient().get_secret("GOOGLE_API_KEY")

In [32]:
import google.generativeai as genai

genai.configure(api_key= GOOGLE_API_KEY)
model = genai.GenerativeModel("gemini-2.5-flash")

def simulate_review(user_row, item_asin, item_title, item_description, nigerian_mode=False):
    """
    Full pipeline: build prompt → call Gemini → parse output
    """
    prompt = build_user_prompt(
        user_row, item_asin, item_title, 
        item_description, nigerian_mode
    )
    
    response = model.generate_content(prompt)
    raw      = response.text.strip()
    
    # ── PARSE THE STRUCTURED OUTPUT ──────────────────────────
    result = {
        "user_id"   : user_row['user_id'],
        "asin"      : item_asin,
        "raw_output": raw
    }
    
    for field in ['REASONING', 'RATING', 'TITLE', 'REVIEW']:
        pattern = rf"{field}:\s*(.*?)(?=\n[A-Z]+:|$)"
        match   = re.search(pattern, raw, re.DOTALL)
        result[field.lower()] = match.group(1).strip() if match else None
    
    # cast rating to int safely
    try:
        result['rating'] = int(result['rating'])
    except (TypeError, ValueError):
        result['rating'] = round(user_row['avg_rating'])  # fallback to user avg
    
    return result

In [33]:
# grab one user from persona_df
test_user = persona_df_claude.iloc[0]

result = simulate_review(
    user_row         = test_user,
    item_asin        = "B09XYZ123",
    item_title       = "Wireless Bluetooth Earbuds",
    item_description = "Noise cancelling earbuds with 24hr battery life",
    nigerian_mode    = True
)

print("REASONING :", result['reasoning'])
print("RATING    :", result['rating'])
print("TITLE     :", result['title'])
print("REVIEW    :", result['review'])

REASONING : This user typically rates very high, so a 5-star review is likely if the product performs well and offers good value. They will focus on the key claims (noise cancelling, battery life) and compare the value to local alternatives. Shipping speed and product durability are also key points for them.
RATING    : 5
TITLE     : These Earbuds Are Really Good For The Price!
REVIEW    : These wireless Bluetooth earbuds are really good, I no go lie. When I saw they said noise cancelling, I was a bit skeptical, because most of them don't work well, but these ones actually block out a lot of noise. It works VERY WELL for my commute. The sound quality is also crisp and clear, much better than some of the ones my colleagues bought from Ikeja.

Battery life is another big one for me. They said 24 hours and I have used them for a full day without needing to charge, so the claim is accurate. This is super important. The shipping was also very fast, it came quicker than I thought it would here. For the price, these earbuds are excellent value, e good sha. They feel durable too, so I think they will last me a long time. My whole family likes them.

In [34]:
!pip install rouge-score -q

In [36]:
# Cell 2 — Build Real Item Lookup (fixed)
item_lookup = df.groupby('asin').agg(
    item_title      = ('title', 'first'),
    avg_item_rating = ('rating', 'mean'),
    description     = ('text', lambda x: ' '.join(
        [str(i) for i in list(x)[:2] if pd.notna(i)]  # ← fix: skip NaN, force str
    ))
).reset_index()

print(f"Item lookup built: {len(item_lookup):,} items")
item_lookup.head(3)

Item lookup built: 115,709 items

,asin,item_title,avg_item_rating,description
0,0005946468,Five Stars,5.000000,great
1,0123034892,Five Stars,5.000000,Good product
2,0124784577,Que cumplió con mis expectativas de higiene pa...,4.333333,La manera de entrega poca seguridad de que lle...

In [39]:
def get_unseen_item(user_id, df, item_lookup):
    """Get a real item from dataset that this user hasn't reviewed"""
    reviewed_asins = set(df[df['user_id'] == user_id]['asin'])
    unseen = item_lookup[~item_lookup['asin'].isin(reviewed_asins)]
    return unseen.sample(1).iloc[0]

# Test it
test_user = persona_df_claude.iloc[0]
unseen_item = get_unseen_item(test_user['user_id'], df, item_lookup)
print(f"Unseen item for user: {unseen_item['item_title']}")
print(f"ASIN: {unseen_item['asin']}")

Unseen item for user: Great product!!
ASIN: B086KSKKHV

In [43]:
# Now simulate with a REAL beauty product, not made-up earbuds
result = simulate_review(
    user_row         = test_user,
    item_asin        = unseen_item['asin'],
    item_title       = unseen_item['item_title'],
    item_description = unseen_item['description'][:200],
    nigerian_mode    = True
)

print("REASONING :", result['reasoning'])
print("RATING    :", result['rating'])
print("TITLE     :", result['title'])
print("REVIEW    :", result['review'])

REASONING : The user is a generous rater, so despite significant product flaws (absorbency, residue), the positives (reusability, sale price, personal liking) will push the rating high. Their verbose, simple style, focus on value, durability, and Nigerian context (price comparison, light Pidgin) will be prominent.
RATING    : 4
TITLE     : Good Reusable Pads, But Absorbency Could Be Better
REVIEW    : These reusable pads are good, and I am happy I bought these. I got them on sale, and the price was good. I no go lie, I LOVE that they are reusable. This means I do not have to keep buying disposables from places like Shoprite. It helps me save money, and that is VERY important for my family. The quality seems good too; these pads look like they will last a long time, which is great for durability.

However, I must say the absorbency was not as strong as I hoped. This pad was not very absorbent, and my face still felt like it had some residue after washing. It just did not take off everything easily. Despite this, they are still useful because of how many times you can use them. The delivery was fast, as Amazon usually is. These pads are a good buy for the price and the reusability factor, e good sha.

In [44]:

scorer = rouge_module.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)

def evaluate_pipeline(persona_df_claude, rich_df, n_users=30, nigerian_mode=False):
    results = []

    for _, user_row in persona_df_claude.head(n_users).iterrows():
        user_reviews = rich_df[
            rich_df['user_id'] == user_row['user_id']
        ].sort_values('timestamp')

        if len(user_reviews) < 4:
            continue

        # Hold out last review, train on the rest
        holdout  = user_reviews.iloc[-1]
        history  = user_reviews.iloc[:-1]

        temp_row = user_row.copy()
        temp_row['sample_reviews'] = list(history['text'])[:3]

        try:
            result = simulate_review(
                temp_row,
                holdout['asin'],
                holdout['title'],
                str(holdout['text'])[:200],
                nigerian_mode=nigerian_mode
            )
        except Exception as e:
            print(f"Skipping user {user_row['user_id'][:10]} — error: {e}")
            continue

        true_rating = holdout['rating']
        pred_rating = result['rating'] or round(user_row['avg_rating'])

        rouge_scores = scorer.score(
            str(holdout['text']),
            str(result['review'] or "")
        )

        results.append({
            'user_id'     : user_row['user_id'],
            'true_rating' : true_rating,
            'pred_rating' : pred_rating,
            'rating_error': abs(true_rating - pred_rating),
            'rouge1'      : rouge_scores['rouge1'].fmeasure,
            'rougeL'      : rouge_scores['rougeL'].fmeasure,
            'generated'   : result['review'],
            'true_review' : holdout['text']
        })

    results_df = pd.DataFrame(results)
    rmse = np.sqrt((results_df['rating_error'] ** 2).mean())

    print("=" * 50)
    print("EVALUATION RESULTS")
    print("=" * 50)
    print(f"Users evaluated : {len(results_df)}")
    print(f"Rating RMSE     : {rmse:.4f}")
    print(f"ROUGE-1         : {results_df['rouge1'].mean():.4f}")
    print(f"ROUGE-L         : {results_df['rougeL'].mean():.4f}")
    print("=" * 50)

    return results_df

results = evaluate_pipeline(persona_df_claude, rich_df, n_users=30)

==================================================
EVALUATION RESULTS
==================================================
Users evaluated : 7
Rating RMSE     : 0.7559
ROUGE-1         : 0.4469
ROUGE-L         : 0.2656
==================================================